### ISSUE TITLE
Moving forward/backward

### ISSUE THREAD

**Issue by levydanqc** [nav9/splitVideoQualityViewer#2]
This tool was exactly what I wanted and I searched a long time before finding it. It's really cool, but it is missing an important feature: moving forward and backward in the movie's timeline.
This missing feature make the tool hard to use for real because we need to stay through the entire start of the movie instead of scrolling to the middle...

Hope to see this feature or at least speed adjustment.

**Comment by nav9** [comment]
Glad to hear the tool is useful, Dan. If you see the readme file, the feature you requested is already in the "Feature upgrades possible" section. I didn't proceed with implementing any feature upgrades as I didn't know if anyone would want them. As of now, if you play two videos, the first of 1 minute duration and the second of 2 minutes duration, when the first one finishes playing, the second one stops being a split video and takes up the entire screen space. So moving the video forward and backward requires some additional planning to re-integrate the first video in split-screen mode.  
I'm the guy who wrote [The Real Cure for Eye Strain](https://nav9.medium.com/the-real-cure-for-eye-strain-6483490d150f), and it's difficult for me to use the computer for long periods of time. I'm currently working on another personal project at a pace I can manage, so any work on the split video quality viewer will take some time to even get started with. If you'd like to fork it and improve it or join as a contributor and improve the project, please feel free to.  
It would help to know what work you do, why and how you use this software, and how many others may be using it.

**Comment by nav9** [comment]
> Hope to see this feature or at least speed adjustment.
I've implemented speed adjustment and seek. Details are in the readme file. When attempting to add the feature, I remembered that I didn't add the seek feature due to [this long standing bug](https://github.com/opencv/opencv/issues/9053) of the seek happening to the wrong frame. I had to use caching to ensure that the video displayed the correct frames on seeking, so you can only seek within any part of the video which has been played normally. So if only one minute of the video has played, you won't be able to seek forward to the second minute of the video. An unfortunate constraint.     
Do try it and see if it feels comfortable to use. I'll wait a while until I close this issue. My apologies for the delay, and I'm glad you raised this issue. It's likely that there would be many others who'd have wanted this feature.

**Comment by nav9** [comment]
@levydanqc : I've added a trackbar which makes moving across the videos simpler. Do try it.  
  
On a side note, if you use such functionality professionally and there are unsolved features with respect to video streaming, playback or encoding, please do let me know.
